Description of demo_cmb_experimental_data
Home > demo > demo_cmb_experimental_data.m
demo_cmb_experimental_data
PURPOSE
-------------------------------------------------------------
SYNOPSIS
This is a script file.
DESCRIPTION
 -------------------------------------------------------------
 Model balancing - Simple test models
 -------------------------------------------------------------
 What this script does:
 o read model and data from SBtab file
 o run model balancing
 o save results to output files
 This script allows you to run model balancing for the four example models in the folder resources/models.
 By default, it uses the example model "branch_point_model".
 To use one of the other models, please uncomment the respective lines in the code.
 To use your own model, please go to "Your model" below and see the instructions
 -------------------------------------------------------------
 How to define a model
 -------------------------------------------------------------
 Files that define model and data:
   network_file       (SBtab filename) SBtab file with tables 'Reaction', 'Compound',
                                          'Position' (optional), 'Parameter' (optional)
   kinetic_data_file  (SBtab filename) SBtab file with table  'ParameterData' (optional; if kinetic_data_file == [],
                                          kinetic data are read from table 'Parameter' in file network_file)
   state_data_file    (SBtab filename) SBtab file with tables 'FluxData',
                                          'MetaboliteConcentrationData', 'EnzymeConcentrationData'
 Other settings:
   model                        (string) model name (freely chosen by the user)
   prb                          (string) estimation scenario name (chosen by the user, should not refer to optimisation settings)
   run                          (string) estimation scenario name (chosen by the user, may refer to optimisation settings)
   file_options.match_data_by   'ModelElementId' (default) or 'KeggId'
   file_options.columns_mean    (cell array of strings) column names for mean data values in metabolite, flux, and enzyme table
   file_options.columns_std     (cell array of strings) column names for std deviations   in metabolite, flux, and enzyme table
   file_options.constraint_file (SBtab filename): file with metabolite bounds (optional; set to [] to use default constraints)
   result_dir                   (directory name) directory for output files (default = matlab's tempdir)
 -------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
cvxpy_problem_data_structure problem = cvxpy_problem_data_structure(network, q_info, prior, data, bounds, true_model, cmb_options)
cmb_load_and_convert_model_and_data [network, q_info, data, c_init, kinetic_data, state_data, conc_min, conc_max] = cmb_load_and_convert_model_and_data(cmb_options, file, file_options)
cmb_default_options cmb_options = cmb_default_options(flag_artificial)
cmb_filenames filenames = cmb_filenames(model_name, prb, run, result_dir, network_sbml_file, flag_artificial)
cmb_model_and_data [bounds, prior, init] = cmb_model_and_data(model, network, data, q_info, c_init, cmb_options)
cmb_resourcedir
This function is called by: