Description of demo_cmb_artificial_data
Home > demo > demo_cmb_artificial_data.m
demo_cmb_artificial_data
PURPOSE
-------------------------------------------------------------------
SYNOPSIS
This is a script file.
DESCRIPTION
 -------------------------------------------------------------------
 Demo script "Model balancing - test with articifial data"
 What this script does:
 o read model from SBML or SBtab file
 o generate artificial data (kinetic constants and state data)
 o run model balancing to try and recover the true model and state data
 -------------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
cmb_default_options cmb_options = cmb_default_options(flag_artificial)
cmb_filenames filenames = cmb_filenames(model_name, prb, run, result_dir, network_sbml_file, flag_artificial)
cmb_model_artificial_data [network, bounds, prior, q_info, data, true, kinetic_data, state_data] = cmb_model_artificial_data(network_file, cmb_options, c_init, position_sbtab_file, constraint_sbtab_file)
cmb_resourcedir
This function is called by: