function report = cmb_statistics(network,cmb_options,prior,data,optimal,calculation_time,res,res_true)

[nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network);

ns = size(data.X.mean,2);
nq = length(prior.q.mean); % WHAT ABOUT THE NUMBER OF INDEPENDENT PARAMETERS????

display(sprintf('----------------'));
display(sprintf('Model statistics'));
display(sprintf('----------------'));

report = {...
    sprintf('Metabolic states:    %d',ns), ...
    sprintf('Metabolites:         %d',nm), ...
    sprintf('Reactions:           %d',nr), ...
    sprintf('KM values:           %d',nKM), ...
    sprintf('KA values:           %d',nKA), ...
    sprintf('KI values:           %d',nKI), ...
    sprintf('Data (kinetic):      %d',sum(isfinite(data.qall.mean))), ...
    sprintf('Data (metabolite):   %d',sum(isfinite(data.X.mean(:)))), ...
    sprintf('Data (enzyme):       %d',sum(isfinite(data.lnE.mean(:)))), ...
    sprintf('Fitted (metabolite): %d',nm*ns), ...
    sprintf('Fitted (enzyme):     %d',nr*ns), ...
    sprintf('Fitted (kinetic):    %d',nq), ...
    sprintf('Fitted (TOTAL):      %d',nm*ns+nr*ns+nq), ...
    sprintf('Enzyme strgcy alpha: %f',cmb_options.enzyme_score_alpha), ...
    sprintf('c/KM stringency beta:%f',cmb_options.beta_ln_c_over_km), ...
    sprintf('Used bounds (1=yes): %d',cmb_options.use_bounds), ...
    sprintf('Used pseudo (1=yes): %d',cmb_options.use_pseudo_values), ...
    sprintf('Used crsscov (1=yes): %d',cmb_options.use_crosscovariances), ...
    sprintf('Initial values type: %s',cmb_options.initial_values_variant), ...
    sprintf('Geom. std errors:    c:%2.3f e:%2.3f Keq:%2.3f Kcatf:%2.3f Kcatr:%2.3f KM:%2.3f',res.c.geometric_deviation, res.e.geometric_deviation, res.Keq.geometric_deviation,res.Kcatf.geometric_deviation,res.Kcatr.geometric_deviation,res.KM.geometric_deviation), ...
    sprintf('Corr. on log scale:  c:%2.3f e:%2.3f Keq:%2.3f Kcatf:%2.3f Kcatr:%2.3f KM:%2.3f',res.c.linear_correlation, res.e.linear_correlation, res.Keq.linear_correlation,res.Kcatf.linear_correlation,res.Kcatr.linear_correlation,res.KM.linear_correlation), ...
    sprintf('Calculation time:    %2.1f s',calculation_time)}';

display(mytable(report,0))