function report = cmb_statistics(network,cmb_options,prior,data,optimal,calculation_time)

[nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network);

ns = size(data.X.mean,2);
nq = length(prior.q.mean); % WHAT ABOUT THE NUMBER OF INDEPENDENT PARAMETERS????

display(sprintf('----------------'));
display(sprintf('Model statistics'));
display(sprintf('----------------'));

report = {...
    sprintf('Metabolic states:    %d',ns), ...
    sprintf('Metabolites:         %d',nm), ...
    sprintf('Reactions:           %d',nr), ...
    sprintf('KM values:           %d',nKM), ...
    sprintf('KA values:           %d',nKA), ...
    sprintf('KI values:           %d',nKI), ...
    sprintf('Data (kinetic):      %d',sum(isfinite(data.qall.mean))), ...
    sprintf('Data (metabolite):   %d',sum(isfinite(data.X.mean(:)))), ...
    sprintf('Data (enzyme):       %d',sum(isfinite(data.lnE.mean(:)))), ...
    sprintf('Fitted (metabolite): %d',nm*ns), ...
    sprintf('Fitted (enzyme):     %d',nr*ns), ...
    sprintf('Fitted (kinetic):    %d',nq), ...
    sprintf('Fitted (TOTAL):      %d',nm*ns+nr*ns+nq), ...
    sprintf('Relaxation alpha:    %f',cmb_options.enzyme_score_alpha), ...
    sprintf('Calculation time:    %2.1f s',calculation_time)}';

display(mytable(report,0))