Description of cmb_estimation
Home > matlab > model-balancing > cmb_estimation.m
cmb_estimation
PURPOSE
[optimal, gradient_V, init, time] = cmb_estimation(network, q_info, bounds, data, prior, preposterior, pp, V, cmb_options)
SYNOPSIS
function [optimal, gradient_V, init, time] = cmb_estimation(network, q_info, bounds, data, prior, preposterior, pp, V, cmb_options)
DESCRIPTION
 [optimal, gradient_V, init, time] = cmb_estimation(network, q_info, bounds, data, prior, preposterior, pp, V, cmb_options)
 gradient_V Gradient of enzyme posterior loss with respect to fluxes (currently not computed)
 --------------------------------------------------------
 Initial guesses for X and q (where preposterior q means: using prior (and possibly data) for q only
 X_init = argmin_X sum(sum( [ [X - preposterior.X.mean] ./ preposterior.X.std ] .^2));  WITHIN allowed polytopes!
 q_init = argmin_X sum(sum( [ [q - preposterior.q.mean] ./ preposterior.q.std     ] .^2);   WITHIN allowed ranges!
 --------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
cmb_qX_to_variables
cmb_qX_to_y
cmb_y_to_qX
cmb_log_posterior
cmb_objective % CURRENTLY NOT USED
This function is called by:
model_balancing [optimal, calculation_time, gradient_V, init, cmb_options, V, kapp_max, preposterior, pp] = model_balancing(filenames, cmb_options, network, q_info, prior, bounds, data, true, init)