Description of cmb_generate_artificial_data
Home > matlab > model-balancing > cmb_generate_artificial_data.m
cmb_generate_artificial_data
PURPOSE
[kinetics, prior, bounds, data, true, kinetic_data, state_data] = cmb_generate_artificial_data(network, cmb_options, q_info)
SYNOPSIS
function [kinetics, prior, bounds, data, true, kinetic_data, state_data] = cmb_generate_artificial_data(network, cmb_options, q_info, c_init, conc_min, conc_max)
DESCRIPTION
 [kinetics, prior, bounds, data, true, kinetic_data, state_data] = cmb_generate_artificial_data(network, cmb_options, q_info)
 Generate an artificial data set for a given metabolic network structure
   network: network structure
   cmb_options  struct containing options
   cmb_options.ns:      number of steady states
   q_info       struct describing the dependencies between model variables
   c_init       (optional) matrix; initial guess of (non-logarithmic) metabolite concentrations;
                           also used for generating the artificial data
   conc_min, conc_max vectors with minimal and maximal metabolite concentrations
   prior        struct describing priors in the optimality problem (details see cmb_make_prior)
   bounds       struct describing bounds in the optimality problem (details see cmb_make_bounds)
   data         struct describing data used in the optimality problem
   true         struct describing true model variables (optional; only for models with artificial data)
CROSS-REFERENCE INFORMATION
This function calls:
cmb_kinetics_to_q
cmb_q_to_qall
cmb_make_bounds
cmb_make_prior the following distribution can be improved (using the results of kinetic parameter balancing)
This function is called by:
cmb_model_artificial_data [network, bounds, prior, q_info, data, true, kinetic_data, state_data] = cmb_model_artificial_data(network_file, cmb_options, c_init, position_sbtab_file, constraint_sbtab_file)
model_balancing [optimal, calculation_time, gradient_V, init, cmb_options, V, kapp_max, preposterior, pp] = model_balancing(filenames, cmb_options, network, q_info, prior, bounds, data, true, init)