Description of cmb_filenames
Home > matlab > model-balancing > cmb_filenames.m
cmb_filenames
PURPOSE
filenames = cmb_filenames(model_name, result_dir, network_sbml_file)
SYNOPSIS
function filenames = cmb_filenames(model_name, run, result_dir, network_sbml_file)
DESCRIPTION
 filenames = cmb_filenames(model_name, result_dir, network_sbml_file)
 Filenames for convex estimation runs
 Input variables
   model_name      (string) model name
   run             (string) run id
   result_dir      Name of output directory (simple string, no directory path)
 Output variables
   filenames struct describing filenames used (constructed using [result_dir] and [run])
CROSS-REFERENCE INFORMATION
This function calls:
cmb_basedir
This function is called by:
demo_cmb_artificial_data -------------------------------------------------------------------
demo_cmb_experimental_data -------------------------------------------------------------
branch_point_model_make_data -------------------------------------------------------------
double_branch_model_make_data -------------------------------------------------------------
three_chain_model_make_data -------------------------------------------------------------