Description of cmb_model_artificial_data
Home > matlab > model-balancing > cmb_model_artificial_data.m
cmb_model_artificial_data
PURPOSE
[network, bounds, prior, q_info, data, true, kinetic_data, state_data] = cmb_model_artificial_data(network_file, cmb_options, c_init, position_sbtab_file, constraint_sbtab_file)
SYNOPSIS
function [network, bounds, prior, q_info, data, true, kinetic_data, state_data, conc_min, conc_max] = cmb_model_artificial_data(network_file, cmb_options, c_init, position_sbtab_file, constraint_sbtab_file)
DESCRIPTION
 [network, bounds, prior, q_info, data, true, kinetic_data, state_data] = cmb_model_artificial_data(network_file, cmb_options, c_init, position_sbtab_file, constraint_sbtab_file)
 Generate input data for a Convex Model Balancing problem with artifical data
 Input variables
   network_file filename of SBML or SBtab network model
   cmb_options  struct containing options
   c_init       (optional) matrix; initial guess of (non-logarithmic) metabolite concentrations;
                           also used for generating the artificial data
   position_sbtab_file (optional) filename of SBtab file (table "Position") for network layout
   constraint_sbtab_file (optional) filename of SBtab file (tables "Position")
 Output variables
   network      struct describing metabolic network (format as in Metabolic Network Toolbox)
   bounds       struct describing bounds in the optimality problem (details see cmb_make_bounds)
   prior        struct describing priors in the optimality problem (details see cmb_make_prior)
   q_info       struct describing the dependencies between model variables
   data         struct describing data used in the optimality problem
   true         struct describing true model variables (optional; only for models with artificial data)
   kinetic_data
   state_data
 For CMB problems with "real" data, use cmb_model_and_data instead
CROSS-REFERENCE INFORMATION
This function calls:
cmb_define_parameterisation q_info = cmb_define_parameterisation(network, cmb_options)
cmb_generate_artificial_data [kinetics, prior, bounds, data, true, kinetic_data, state_data] = cmb_generate_artificial_data(network, cmb_options, q_info)
This function is called by:
demo_cmb_artificial_data -------------------------------------------------------------------
branch_point_model_make_data -------------------------------------------------------------
double_branch_model_make_data -------------------------------------------------------------
three_chain_model_make_data -------------------------------------------------------------