Description of cmb_model_and_data
Home > matlab > model-balancing > cmb_model_and_data.m
cmb_model_and_data
PURPOSE
[bounds, prior, init] = cmb_model_and_data(model, network, data, q_info, c_init, cmb_options)
SYNOPSIS
function [bounds, prior, init] = cmb_model_and_data(model, network, data, q_info, c_init, cmb_options, conc_min, conc_max)
DESCRIPTION
 [bounds, prior, init] = cmb_model_and_data(model, network, data, q_info, c_init, cmb_options)
 Prepare data structures describing a Convex Model Balancing problem
 Input variables
   model        (string) model name
   network      struct describing metabolic network (format as in Metabolic Network Toolbox)
   data         struct describing data used in the optimality problem
   q_info       struct describing the dependencies between model variables
   c_init       matrix; initial guess of (non-logarithmic) metabolite concentrations
   cmb_options  struct containing options
   conc_min, conc_max vectors of minimal and maximal metabolite concentrations
 Output variables
   bounds    struct describing bounds in the optimality problem (details see cmb_make_bounds)
   prior     struct describing priors in the optimality problem (details see cmb_make_prior)
   init      struct containing the initial model variables (fields init.q and init.X)
 For problems with artificial data, use cmb_model_artificial_data instead
CROSS-REFERENCE INFORMATION
This function calls:
cmb_kinetics_to_q
cmb_make_bounds
cmb_make_prior the following distribution can be improved (using the results of kinetic parameter balancing)
This function is called by:
demo_cmb_experimental_data -------------------------------------------------------------