Description of cmb_prior_file
Home > matlab > model-balancing > cmb_prior_file.m
cmb_prior_file
PURPOSE
SYNOPSIS
function prior_file = cmb_prior_file()
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
cmb_basedir
This function is called by:
cmb_load_model_and_data [network, kinetic_data, state_data, conc_min, conc_max] = cmb_load_model_and_data(model_file, kinetic_data_file, state_data_files, replace_ids_in_network, match_data_by, constraint_sbtab_file)
cmb_default_options cmb_options = cmb_default_options()