Description of cmb_q_to_qall
Home > cmb > functions > variables > cmb_q_to_qall.m
cmb_q_to_qall
PURPOSE
SYNOPSIS
function qall = cmb_q_to_qall(q, q_info)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cmb_generate_artificial_data [kinetics, prior, bounds, data, true] = cmb_generate_artificial_data(network, cmb_options, q_info)
cmb_graphics ---------------------
e_coli_glucose_model_and_data_from_ECM --------------------------------------------------------------