Description of cmb_log_posterior
Home > cmb > functions > cmb_log_posterior.m
cmb_log_posterior
PURPOSE
SYNOPSIS
function [log_posterior,log_posterior_gradient] = cmb_log_posterior(y,pp,preposterior,V,cmb_options,q_info,verbose)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
cmb_qX_to_y
cmb_q_to_kinetics
cmb_y_to_qX
This function is called by:
cmb_display_scores
cmb_estimation [optimal, gradient_V, init, time] = cmb_estimation(network, q_info, bounds, data, prior, preposterior, pp, V, cmb_options)
cmb_objective % CURRENTLY NOT USED