Description of cmb_basedir
Home > cmb > functions > cmb_basedir.m
cmb_basedir
PURPOSE
SYNOPSIS
function d = cmb_basedir()
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cmb_model_artificial_data set filenames
cmb_prior_file
e_coli_davidi_2016_convert_data Read omics data from Davidi 2016 and Map BIGG reaction IDs and gene names to KEGG reaction IDs
e_coli_davidi_2016_data_filenames State data files for one metabolic state:
e_coli_c_init --------------------------------------------------------------
e_coli_glucose_data_filenames State data files for one mebtabolic state:
e_coli_glucose_kinetic_data_filenames Kinetic data files
e_coli_glucose_model_and_data_from_ECM --------------------------------------------------------------
small_model_make_network -------------------------------------------------------------