Description of convex_model_balancing
Home > cmb > functions > convex_model_balancing.m
convex_model_balancing
PURPOSE
SYNOPSIS
function [optimal, calculation_time, gradient_V, init, cmb_options, V, kapp_max, preposterior, pp] = model_balancing(filenames, cmb_options, network, q_info, prior, bounds, data, true)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
cmb_display_scores
cmb_estimation [optimal, gradient_V, init, time] = cmb_estimation(network, q_info, bounds, data, prior, preposterior, pp, V, cmb_options)
cmb_generate_artificial_data [kinetics, prior, bounds, data, true] = cmb_generate_artificial_data(network, cmb_options, q_info)
cmb_graphics ---------------------
cmb_make_pp Structure pp contains the network and other information (needed to call ecm enzyme cost score function)
cmb_prepare_posterior --------------------------------------------------------
cmb_save_results save results of model balancing as SBtab files
cmb_statistics
convex_model_balancing
cmb_define_parameterisation q_info = cmb_define_parameterisation(network, cmb_options)
This function is called by:
convex_model_balancing