Description of branch_point_model_make_data
Home > resources > models > branch_point_model > matlab > branch_point_model_make_data.m
branch_point_model_make_data
PURPOSE
-------------------------------------------------------------
SYNOPSIS
This is a script file.
DESCRIPTION
 -------------------------------------------------------------
 Artificial data for branch point model
 This script generates the artificial data files
 in      ~/resources/models/double_branch_model/data
 used in demo_cmb_experimental_data.m
 -------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
cmb_default_options cmb_options = cmb_default_options()
cmb_filenames filenames = cmb_filenames(model_name, result_dir, network_sbml_file)
cmb_model_artificial_data [network, bounds, prior, q_info, data, true, kinetic_data, state_data] = cmb_model_artificial_data(network_file, cmb_options, c_init, position_sbtab_file, constraint_sbtab_file)
cmb_resourcedir
This function is called by: