Description of cmb_variables_to_log_posterior
Home > model-balancing > cmb_variables_to_log_posterior.m
cmb_variables_to_log_posterior
PURPOSE
f = cmb_variables_to_log_posterior(kinetics,X)
SYNOPSIS
function f = cmb_variables_to_log_posterior(kinetics,X,network,q_info,cmb_options,prior,data,verbose)
DESCRIPTION
 f = cmb_variables_to_log_posterior(kinetics,X)
 wrapper function around  cmb_log_posterior, using the original variables (not the vector y) as inputs
CROSS-REFERENCE INFORMATION
This function calls:
cmb_kinetics_to_q
cmb_qX_to_y
cmb_q_to_qall
cmb_log_posterior [log_posterior,log_posterior_gradient] = cmb_log_posterior(y,pp,preposterior,V,cmb_options,q_info,verbose)
cmb_make_pp Structure pp contains the network and other information (needed to call ecm enzyme cost score function)
cmb_prepare_posterior --------------------------------------------------------
This function is called by: