Description of e_coli_glucose_model_and_data
Home > cmb > models > e_coli_noor_2016 > e_coli_glucose_model_and_data.m
e_coli_glucose_model_and_data
PURPOSE
% Generic function for reading models and data - does not yield a good initial state!
SYNOPSIS
function [network, q_info, data, c_init, kinetic_data, state_data] = e_coli_glucose_model_and_data(cmb_options)
DESCRIPTION
% Generic function for reading models and data - does not yield a good initial state!
CROSS-REFERENCE INFORMATION
This function calls:
cmb_load_model_and_data [network, kinetic_data, state_data] = cmb_load_model_and_data(model_file, kinetic_data_file, metabolite_data_file, enzyme_data_file, flux_data_file)
cmb_state_data_to_data
cmb_define_parameterisation q_info = cmb_define_parameterisation(network, cmb_options)
e_coli_glucose_data_filenames State data files for one mebtabolic state:
e_coli_glucose_kinetic_data_filenames Kinetic data files
This function is called by: