Description of model_balancing
Home > matlab > model_balancing.m
model_balancing
PURPOSE
[optimal, calculation_time, gradient_V, init, cmb_options, V, kapp_max, preposterior, pp] = model_balancing(filenames, cmb_options, network, q_info, prior, bounds, data, true, init)
SYNOPSIS
function [optimal, calculation_time, gradient_V, init, cmb_options, V, kapp_max, preposterior, pp] = model_balancing(filenames, cmb_options, network, q_info, prior, bounds, data, true, init)
DESCRIPTION
 [optimal, calculation_time, gradient_V, init, cmb_options, V, kapp_max, preposterior, pp] = model_balancing(filenames, cmb_options, network, q_info, prior, bounds, data, true, init)
 Convex model balancing
 For input and output variables, see the demo files
 Input variables:
   filenames    struct, (model- and run-specific) filenames for input and output files
     .graphics_dir optional; output directory for saving graphics
     .report_txt   optional; output report file (.txt)
     .results_mat  optional;  output results file (.mat)
   cmb_options  struct, options
   network      struct, metabolic network (format as in Metabolic Network Toolbox)
   q_info       struct, the dependencies between model variables
   prior        struct, priors in the optimality problem (details see cmb_make_prior)
   bounds       struct, bounds in the optimality problem (details see cmb_make_bounds)
   data         struct, data used in the optimality problem
                  flux maxtrix: data.V.mean
   true         struct, true model variables (optional; only for models with artificial data)
   init         struct, initial values
 Output variables:
   optimal          struct containing the model variables obtained from optimisation
   calculation_time calculation time in seconds
   gradient_V       gradient of enzyme posterior loss w.r.t. fluxes (currently not computed)
   init             struct containing the initial model variables (fields init.q and init.X)
   cmb_options      struct containing options (updated by the function)
   V                flux data
   kapp_max         struct containing kapp_max values
   preposterior     struct containing the preposterior distribution
   pp               struct containing some data used during calculation (see cmb_make_pp(network))
 For generating the input data, see 'cmb_model_and_data' and 'cmb_model_artificial_data'
CROSS-REFERENCE INFORMATION
This function calls:
cmb_save_results cmb_save_results(network, data, optimal, filenames, cmb_options, options)
cmb_define_parameterisation q_info = cmb_define_parameterisation(network, cmb_options)
cmb_display_scores
cmb_estimation [optimal, gradient_V, init, time] = cmb_estimation(network, q_info, bounds, data, prior, preposterior, pp, V, cmb_options)
cmb_generate_artificial_data [kinetics, prior, bounds, data, true, kinetic_data, state_data] = cmb_generate_artificial_data(network, cmb_options, q_info)
cmb_graphics
cmb_make_pp Structure pp contains the network and other information (needed to call ecm enzyme cost score function)
cmb_prepare_posterior --------------------------------------------------------
cmb_statistics
model_balancing [optimal, calculation_time, gradient_V, init, cmb_options, V, kapp_max, preposterior, pp] = model_balancing(filenames, cmb_options, network, q_info, prior, bounds, data, true, init)
This function is called by:
demo_cmb_artificial_data -------------------------------------------------------------------
demo_cmb_experimental_data -------------------------------------------------------------
model_balancing [optimal, calculation_time, gradient_V, init, cmb_options, V, kapp_max, preposterior, pp] = model_balancing(filenames, cmb_options, network, q_info, prior, bounds, data, true, init)